// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBf4LU5ER5dideQiL6YDSPIUOBgeanZY_4',
    appId: '1:224123066078:web:2439d3a3985cdb1f48144f',
    messagingSenderId: '224123066078',
    projectId: 'shappar-c22d7',
    authDomain: 'shappar-c22d7.firebaseapp.com',
    storageBucket: 'shappar-c22d7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEID28E6bXz6D6ltFVUr-eIoKEGqDmqSs',
    appId: '1:224123066078:android:403c6c6225eb7d3d48144f',
    messagingSenderId: '224123066078',
    projectId: 'shappar-c22d7',
    storageBucket: 'shappar-c22d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDffcro9cKFSJmtNglpOhkWKW63BI5b-OI',
    appId: '1:224123066078:ios:2f866ae70fdb79b248144f',
    messagingSenderId: '224123066078',
    projectId: 'shappar-c22d7',
    storageBucket: 'shappar-c22d7.appspot.com',
    iosBundleId: 'com.example.projectShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDffcro9cKFSJmtNglpOhkWKW63BI5b-OI',
    appId: '1:224123066078:ios:a1e4d8297ef81e3348144f',
    messagingSenderId: '224123066078',
    projectId: 'shappar-c22d7',
    storageBucket: 'shappar-c22d7.appspot.com',
    iosBundleId: 'com.example.projectShop.RunnerTests',
  );
}
